add_item:
  description: Add an item to the Anylist list
  fields:
    name:
      description: Name of the item
      example: Milk
      selector:
        text:
    list:
      description: Name of the list
      example: Shopping
      selector:
        text:
    notes:
      description: Notes for the item
      example: Skim Milk
      selector:
        text:

remove_item:
  description: Remove an item from the Anylist list
  fields:
    name:
      description: Name of the item
      example: Milk
      selector:
        text:
    list:
      description: Name of the list
      example: Shopping
      selector:
        text:

get_items:
  description: Gets the list of items that are on the Anylist list
  fields:
    list:
      description: Name of the list
      example: Shopping
      selector:
        text:

check_item:
  description: Check an item from the Anylist list
  fields:
    name:
      description: Name of the item
      example: Milk
      selector:
        text:
    list:
      description: Name of the list
      example: Shopping
      selector:
        text:

uncheck_item:
  description: Uncheck an item from the Anylist list
  fields:
    name:
      description: Name of the item
      example: Milk
      selector:
        text:
    list:
      description: Name of the list
      example: Shopping
      selector:
        text:
