add_item:
  description: Add an item to the Anylist list
  fields:
    name:
      description: Name of the item
      example: Milk
      selector:
        text:
    list:
      description: Name of the list
      example: Shopping
      selector:
        text:
    notes:
      description: Notes for the item
      example: Skim Milk
      selector:
        text:

remove_item:
  description: Remove an item from the Anylist list
  fields:
    name:
      description: Name of the item
      example: Milk
      selector:
        text:
    list:
      description: Name of the list
      example: Shopping
      selector:
        text:

get_items:
  description: Gets the list of unchecked items that are on the Anylist list
  fields:
    list:
      description: Name of the list
      example: Shopping
      selector:
        text:

get_all_items:
  description: Gets the list of unchecked items and also checked / completed items that are on the Anylist list
  fields:
    list:
      description: Name of the list
      example: Shopping
      selector:
        text:

check_item:
  description: Check an item from the Anylist list
  fields:
    name:
      description: Name of the item
      example: Milk
      selector:
        text:
    list:
      description: Name of the list
      example: Shopping
      selector:
        text:

uncheck_item:
  description: Uncheck an item from the Anylist list
  fields:
    name:
      description: Name of the item
      example: Milk
      selector:
        text:
    list:
      description: Name of the list
      example: Shopping
      selector:
        text:

get_mealplan:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: anylist
    start_date:
      selector:
        date:
    end_date:
      selector:
        date:

get_recipe:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: anylist
    recipe_id:
      required: true
      selector:
        text:

import_recipe:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: anylist
    url:
      required: true
      selector:
        text:
    include_tags:
      selector:
        boolean:

set_random_mealplan:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: anylist
    date:
      selector:
        date:
    entry_type:
      selector:
        select:
          options:
            - breakfast
            - lunch
            - dinner
            - side
          translation_key: mealplan_entry_type

set_mealplan:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: anylist
    date:
      selector:
        date:
    entry_type:
      selector:
        select:
          options:
            - breakfast
            - lunch
            - dinner
            - side
          translation_key: mealplan_entry_type
    recipe_id:
      selector:
        text:
    note_title:
      selector:
        text:
    note_text:
      selector:
        text:
